<template>
  <el-menu
      :uniqueOpened="true"
      default-active="2"
      class="el-menu-vertical-demo"
      @open="handleOpen"
      @close="handleClose"
      background-color="#545c64"
      text-color="#fff"
      active-text-color="#ffd04b">
    <el-submenu v-for="menu in menus" :key="menu.name" :index="menu.name">
      <template #title>
        <i class="icon iconfont" :class="menu.icon != ''?menu.icon:''"></i>
        <span>{{menu.name}}</span>
      </template>
      <el-menu-item v-for="item in menu.children" :key="menu.name + '-' + item.name" :index="menu.name + '-' + item.name">
        <i class="icon iconfont" :class="item.icon"></i>
        <span>{{item.name}}</span>
      </el-menu-item>
    </el-submenu>
  </el-menu>
</template>
<script>
export default {
  name: "Index",
  data(){
    return{
      menus:[
        {
          icon:'icon-huifang',
          name:'回访系统',
          path:'',
          children:[
            {
              icon:'icon-boda',
              name:'回访任务拨打',
              path:'',
            },
            {
              icon:'icon-chaxun',
              name:'回访情况查询',
              path:'',
            },
            {
              icon:'icon-guanli',
              name:'回访项目管理',
              path:'',
            },
            {
              icon:'icon-guanli',
              name:'回访权限配置',
              path:'',
            },
            {
              icon:'icon-wenjuan',
              name:'问卷配置',
              path:'',
            },
            {
              icon:'icon-wenjuan',
              name:'问题简述配置',
              path:'',
            }
          ]
        },
        {
          icon:'icon-gongdan',
          name:'工单系统',
          path:'',
          children:[
            {
              icon:'icon-chuangjian',
              name:'创建工单',
              path:'',
            },
            {
              icon:'',
              name:'待办工单',
              path:'',
            },
            {
              icon:'icon-chaxun',
              name:'工单查询',
              path:'',
            },
            {
              icon:'icon-guanli',
              name:'工单流程管理',
              path:'',
            },
            {
              icon:'icon-fenlei',
              name:'工单原因分类',
              path:'',
            }
          ]
        },
        {
          icon:'icon-luyin',
          name:'录音平台',
          path:'',
          children:[
            {
              icon:'',
              name:'录音查听',
              path:'',
            },
            {
              icon:'',
              name:'留言查听',
              path:'',
            },
            {
              icon:'',
              name:'我的录音',
              path:'',
            }
          ]
        },
        {
          icon:'icon-zhishi',
          name:'知识管理',
          path:'',
          children:[
            {
              icon:'',
              name:'知识目录',
              path:'',
            },
            {
              icon:'',
              name:'即将过期的知识',
              path:'',
            },
            {
              icon:'icon-daiban',
              name:'已过期的知识',
              path:'',
            },
            {
              icon:'icon-daiban',
              name:'知识管理',
              path:'',
            }
          ]
        },
        {
          icon:'icon-zhijiandan_huaban',
          name:'质检系统',
          path:'',
          children:[
            {
              icon:'icon-chaxun',
              name:'质检查询',
              path:'',
            },
            {
              icon:'icon-renwu',
              name:'任务质检',
              path:'',
            },
            {
              icon:'',
              name:'质检分配',
              path:'',
            },
            {
              icon:'icon-shenhe',
              name:'质检审核',
              path:'',
            },
            {
              icon:'',
              name:'质检复议',
              path:'',
            },
            {
              icon:'',
              name:'模板管理',
              path:'',
            }
          ]
        },
        {
          icon:'icon-zixun',
          name:'咨询业务',
          path:'',
          children:[
            {
              icon:'icon-boda',
              name:'呼入工作台',
              path:'',
            },
            {
              icon:'icon-jilu',
              name:'服务记录单',
              path:'',
            },
            {
              icon:'icon-fenlei',
              name:'来电原因管理',
              path:'',
            }
          ]
        },
        {
          icon:'icon-duanxin',
          name:'短信系统',
          path:'',
          children:[
            {
              icon:'icon-chaxun',
              name:'短信记录查询',
              path:'',
            },
            {
              icon:'icon-faduanxin',
              name:'发送短信',
              path:'',
            },
            {
              icon:'icon-guanli',
              name:'模板管理',
              path:'',
            }
          ]
        },
        {
          icon:'icon-gonggao',
          name:'公告系统',
          path:'',
          children:[
            {
              icon:'',
              name:'跑马灯',
              path:'',
            },
            {
              icon:'',
              name:'发布公告',
              path:'',
            },
            {
              icon:'icon-guanli',
              name:'公告管理',
              path:'',
            }
          ]
        },
        {
          icon:'icon-anquan',
          name:'安全设置',
          path:'',
          children:[
            {
              icon:'icon-iconfontmima',
              name:'修改密码',
              path:'',
            },
            {
              icon:'icon-shenhe',
              name:'登录审核',
              path:'',
            }
          ]
        },
        {
          icon:'icon-liaotianjilu',
          name:'在线客服',
          path:'',
          children:[
            {
              icon:'',
              name:'在线工作台',
              path:'',
            },
            {
              icon:'',
              name:'在线留言',
              path:'',
            },
            {
              icon:'icon-liaotianjilu',
              name:'聊天记录查询',
              path:'',
            },
            {
              icon:'',
              name:'快捷回复',
              path:'',
            }
          ]
        },
        {
          icon:'icon-jianyi',
          name:'建议反馈',
          path:'',
          children:[
            {
              icon:'',
              name:'我的建议',
              path:'',
            },
            {
              icon:'',
              name:'建议查询',
              path:'',
            },
            {
              icon:'',
              name:'创建建议',
              path:'',
            }
          ]
        },
        {
          icon:'icon-jiankong',
          name:'监控系统',
          path:'',
          children:[
            {
              icon:'',
              name:'坐席状态监控',
              path:'',
            },
            {
              icon:'',
              name:'系统状态监控',
              path:'',
            },
            {
              icon:'',
              name:'异常数据监控',
              path:'',
            }
          ]
        },
        {
          icon:'icon-paibanguanli',
          name:'劳动力管理',
          path:'',
          children:[
            {
              icon:'',
              name:'排班管理',
              path:'',
            },
            {
              icon:'',
              name:'班次管理',
              path:'',
            },
            {
              icon:'',
              name:'班组管理',
              path:'',
            },
            {
              icon:'',
              name:'班表管理',
              path:'',
            },
            {
              icon:'',
              name:'排班轨迹',
              path:'',
            },
            {
              icon:'',
              name:'排班查询',
              path:'',
            }
          ]
        },
        {
          icon:'icon-baobiao',
          name:'报表系统',
          path:'',
          children:[
            {
              icon:'',
              name:'回访清单',
              path:'',
            },
            {
              icon:'',
              name:'工单明细',
              path:'',
            },
            {
              icon:'',
              name:'质检综合指标',
              path:'',
            },
            {
              icon:'',
              name:'IVR综合明细',
              path:'',
            },
            {
              icon:'',
              name:'坐席综合明细',
              path:'',
            }
          ]
        },
        {
          icon:'icon-shezhi',
          name:'系统配置',
          path:'',
          children:[
            {
              icon:'icon-caidan',
              name:'菜单配置',
              path:'',
            },
            {
              icon:'',
              name:'公共变量',
              path:'',
            },
            {
              icon:'',
              name:'功能权限管理',
              path:'',
            }
          ]
        },
        {
          icon:'icon-quanxian',
          name:'权限管理',
          path:'',
          children:[
            {
              icon:'',
              name:'用户管理',
              path:'',
            },
            {
              icon:'',
              name:'角色管理',
              path:'',
            },
            {
              icon:'icon-institute',
              name:'机构配置',
              path:'',
            }
          ]
        },
        {
          icon:'icon-youjian',
          name:'邮件系统',
          path:'',
          children:[
            {
              icon:'',
              name:'邮件查询',
              path:'',
            },
            {
              icon:'',
              name:'发送邮件',
              path:'',
            },
            {
              icon:'',
              name:'邮件模板',
              path:'',
            }
          ]
        }
      ]
    }
  },
  methods: {
    handleOpen(key, keyPath) {
      console.log(key, keyPath);
    },
    handleClose(key, keyPath) {
      console.log(key, keyPath);
    }
  }
}
</script>
<style scoped>
.iconfont{
  color: #c9c9c9;
  margin-right: 10px;
}

</style>
